<a href="https://colab.research.google.com/github/Syeda1234769/Pandas/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Syeda Azka Batool
# 875669

In [ ]:
import pandas as pd

In [ ]:
# Task 1
data = {
    "Name": ["Ali","Sara", "Ahmed", "Ayesha", "Zain"],
    "Marks": [70, 85, 60, 95, 45]
}
df = pd.DataFrame(data)
print(df)
average_marks = df["Marks"].mean()
print("Average Marks:", average_marks)
maximum_marks = df["Marks"].max()
print("Maximum Marks:", maximum_marks)
minimum_marks = df["Marks"].min()
print("Minimum Marks:", minimum_marks)
total_students = len(df)
print("Total Students:", total_students)

     Name  Marks
0     Ali     70
1    Sara     85
2   Ahmed     60
3  Ayesha     95
4    Zain     45
Average Marks: 71.0
Maximum Marks: 95
Minimum Marks: 45
Total Students: 5

In [ ]:
# Task 2

print("Students marks >= 50:")
print(df[df["Marks"] >= 50])

print("Students marks < 50:")
print(df[df["Marks"] < 50])

Students marks >= 50:
     Name  Marks
0     Ali     70
1    Sara     85
2   Ahmed     60
3  Ayesha     95
Students marks < 50:
   Name  Marks
4  Zain     45

In [ ]:
# Task 3
df["City"] = ["Karachi", "Lahore", "Islamabad", "Punjab", "Karachi"]
print(df[df["City"] == "Karachi"])

   Name  Marks     City
0   Ali     70  Karachi
4  Zain     45  Karachi

In [ ]:
# Task 4
data = {
    "Name": ["Ali","Sara", "Ahmed", "Ayesha", "Zain"],
    "Courses": ["AI", "Web", "AI", "Web", "AI"],
    "Marks": [70, 85, 60, 95, 45]
}
df = pd.DataFrame(data)

result = df.groupby("Courses")["Marks"].mean()
print(result)

Courses
AI     58.333333
Web    90.000000
Name: Marks, dtype: float64

In [ ]:
# Task 5
data = {
    "Name": ["Ali","Sara", "Ahmed", "Ayesha", "Zain"],
    "Marks": [70, None, 60, None, 45]
}
df = pd.DataFrame(data)
print(df)
print("Missing values:")
print(df["Marks"].isnull().sum())
average = df["Marks"].mean()
print("Average:", average)
df["Marks"] = df["Marks"].fillna(average)
print(df)

     Name  Marks
0     Ali   70.0
1    Sara    NaN
2   Ahmed   60.0
3  Ayesha    NaN
4    Zain   45.0
Missing values:
2
Average: 58.333333333333336
     Name      Marks
0     Ali  70.000000
1    Sara  58.333333
2   Ahmed  60.000000
3  Ayesha  58.333333
4    Zain  45.000000

# CREATING A DATAFRAME

In [ ]:
data = {
    "Name": ["Ali", "Sara", "Ahmed"],
    "Age": [20, 21, 19],
    "Marks": [80, 90, 75],
    "Gender": ["Male", "Female", "Male"]
}

ds = pd.DataFrame(data)

print(ds)

    Name  Age  Marks  Gender
0    Ali   20     80    Male
1   Sara   21     90  Female
2  Ahmed   19     75    Male

# READING A DATASET

In [ ]:
ds = pd.read_csv("/content/sample_data/Social_media_impact_on_life.csv")
ds

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial
4496,STU_2028496,19,Female,Undergraduate,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,Frequently,9.0,83,3.37,Beneficial
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial

# VIEWING DATA

In [ ]:
# 1.head()
(ds.head())

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial

In [ ]:
# 2.tail()
(ds.tail())

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial
4496,STU_2028496,19,Female,Undergraduate,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,Frequently,9.0,83,3.37,Beneficial
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial

In [ ]:
# 3.sample
(ds.sample())

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
26,STU_2024026,20,Female,Undergraduate,Instagram,4.3,1.4,Smartphone,8.1,3,False,Frequently,2.0,95,3.37,Beneficial

# SHAPE AND BASIC PROPERTIES

In [ ]:
# 1.shape()
print(ds.shape)

(4500, 16)

In [ ]:
# 2.columns names()
(ds.columns)

Index(['Student_ID', 'Age', 'Gender', 'Academic_Level', 'Primary_Platform',
       'Daily_Usage_Hours', 'Weekend_Extra_Hours', 'Device_Type',
       'Sleep_Duration_Hours', 'Sleep_Quality_Score', 'Late_Night_Usage',
       'Social_Comparison_Frequency', 'Perceived_Stress_Score',
       'Mental_Health_Index', 'Academic_Performance_GPA', 'Overall_Impact'],
      dtype='object')

In [ ]:
# 3.data type()
(ds.dtypes)

Student_ID                      object
Age                              int64
Gender                          object
Academic_Level                  object
Primary_Platform                object
Daily_Usage_Hours              float64
Weekend_Extra_Hours            float64
Device_Type                     object
Sleep_Duration_Hours           float64
Sleep_Quality_Score              int64
Late_Night_Usage                  bool
Social_Comparison_Frequency     object
Perceived_Stress_Score         float64
Mental_Health_Index              int64
Academic_Performance_GPA       float64
Overall_Impact                  object
dtype: object

# DATAFRAME INFORMATION

In [ ]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Student_ID                   4500 non-null   object
 1   Age                          4500 non-null   int64
 2   Gender                       4500 non-null   object
 3   Academic_Level               4500 non-null   object
 4   Primary_Platform             4500 non-null   object
 5   Daily_Usage_Hours            4500 non-null   float64
 6   Weekend_Extra_Hours          4500 non-null   float64
 7   Device_Type                  4500 non-null   object
 8   Sleep_Duration_Hours         4500 non-null   float64
 9   Sleep_Quality_Score          4500 non-null   int64
 10  Late_Night_Usage             4500 non-null   bool
 11  Social_Comparison_Frequency  4500 non-null   object
 12  Perceived_Stress_Score       4454 non-null   float64
 13  Mental_Health_Index          4500 non-null   int64
 14  Academic_Performance_GPA     4415 non-null   float64
 15  Overall_Impact               4500 non-null   object
dtypes: bool(1), float64(5), int64(3), object(7)
memory usage: 531.9+ KB

# STATISTICAL SUMMARY

In [ ]:
(ds.describe())

,Age,Daily_Usage_Hours,Weekend_Extra_Hours,Sleep_Duration_Hours,Sleep_Quality_Score,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA
count,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4454.000000,4500.000000,4415.000000
mean,18.703333,5.295933,1.796844,6.701333,2.472000,13.512124,79.873111,3.429282
std,1.981182,2.604497,0.699245,1.189998,1.030484,7.072859,12.876044,0.392662
min,15.000000,0.900000,0.000000,3.000000,1.000000,0.000000,32.000000,1.900000
25%,17.000000,3.400000,1.300000,6.000000,2.000000,9.000000,72.000000,3.200000
50%,19.000000,4.700000,1.800000,6.800000,3.000000,13.000000,82.000000,3.460000
75%,20.000000,6.600000,2.300000,7.500000,3.000000,18.000000,89.000000,3.720000
max,26.000000,14.000000,4.500000,10.500000,5.000000,40.000000,98.000000,4.000000

# SELECTING COLUMNS

In [ ]:
(ds["Age"])

0       19
1       19
2       17
3       16
4       17
        ..
4495    16
4496    19
4497    19
4498    16
4499    24
Name: Age, Length: 4500, dtype: int64

In [ ]:
(ds["Daily_Usage_Hours"])

0        7.5
1        4.6
2       10.9
3        6.0
4        3.3
        ...
4495     5.8
4496     3.8
4497     7.7
4498     4.6
4499     1.8
Name: Daily_Usage_Hours, Length: 4500, dtype: float64

# SELECTING MULTIPLE COLUMNS

In [ ]:
(ds[["Age", "Gender"]])

      Age  Gender
0      19  Female
1      19  Female
2      17  Female
3      16  Female
4      17    Male
...   ...     ...
4495   16    Male
4496   19  Female
4497   19    Male
4498   16    Male
4499   24    Male

[4500 rows x 2 columns]

# SELECTING ROWS

In [ ]:
# 1.loc[]
(ds.loc[[3500,50]])

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
3500,STU_2027500,18,Male,Undergraduate,Reddit,12.2,0.0,Smartphone,4.9,1,True,Sometimes,25.0,45,2.38,Negative
50,STU_2024050,15,Female,High School,TikTok,8.6,1.0,Smartphone,6.4,1,True,Rarely,11.0,66,3.38,Beneficial

In [ ]:
# to get a specify value
(ds.loc[5, "Gender"])

'Male'

In [ ]:
# iloc
(ds.iloc[0,3])

'Undergraduate'

In [ ]:
# to get the specific row and column
(ds.iloc[1, 14])

np.float64(3.21)

# FILTERING DATA

In [ ]:
age_above_or_equal_to_19 = ds[ds["Age"]>=19]
(age_above_or_equal_to_19)

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
6,STU_2024006,20,Male,Undergraduate,TikTok,5.6,1.8,Smartphone,8.3,3,False,Sometimes,10.0,88,3.72,Beneficial
7,STU_2024007,19,Female,Undergraduate,TikTok,1.2,2.4,Smartphone,8.1,5,False,Always,6.0,95,3.37,Beneficial
11,STU_2024011,20,Male,Undergraduate,LinkedIn,7.8,1.4,Smartphone,7.2,2,True,Sometimes,17.0,76,3.08,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4490,STU_2028490,19,Male,Undergraduate,TikTok,4.0,1.8,Smartphone,6.3,3,False,Sometimes,13.0,74,4.00,Beneficial
4492,STU_2028492,22,Male,Postgraduate,Snapchat,3.6,2.5,Smartphone,7.0,4,True,Frequently,11.0,92,3.42,Beneficial
4496,STU_2028496,19,Female,Undergraduate,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,Frequently,9.0,83,3.37,Beneficial
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial

In [ ]:
age_below_19 = ds[ds["Age"]<19]
(age_below_19)

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial
5,STU_2024005,16,Male,High School,TikTok,6.2,1.6,Smartphone,5.9,1,False,Rarely,10.0,66,3.21,Beneficial
8,STU_2024008,18,Female,Undergraduate,YouTube,3.3,1.8,Smartphone,6.4,2,False,Frequently,23.0,88,3.59,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4491,STU_2028491,18,Female,High School,YouTube,9.7,1.9,Smartphone,4.2,1,True,Sometimes,21.0,63,2.73,Neutral
4493,STU_2028493,18,Female,Undergraduate,YouTube,4.5,2.4,Smartphone,8.2,4,True,Sometimes,0.0,85,3.75,Beneficial
4494,STU_2028494,16,Male,High School,YouTube,5.2,1.6,Smartphone,5.7,3,True,Sometimes,24.0,77,3.31,Neutral
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial

# ADDING A NEW COLUMN

In [ ]:
# Adding A Column
cities = ["Karachi", "Faisalabad", "Rawalpindi", "Lahore", "Islamabad", "Peshawar", "Quetta", "Multan"]
ds["City"] = (cities * 563)[:4500]
(ds)

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact,City
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral,Karachi
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial,Faisalabad
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral,Rawalpindi
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial,Lahore
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial,Islamabad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial,Multan
4496,STU_2028496,19,Female,Undergraduate,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,Frequently,9.0,83,3.37,Beneficial,Karachi
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial,Faisalabad
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial,Rawalpindi
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial,Lahore

In [ ]:
# adding a column
data = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha"],
    "Marks": [45, 90, 75, 40]
}

df = pd.DataFrame(data)
df["Gender"] =["Male", "Female", "Male", "Female"]
(df)
# create a column using calculations
df["Bonus Marks"] = df["Marks"] + 5

print(df)

     Name  Marks  Gender  Bonus Marks
0     Ali     45    Male           50
1    Sara     90  Female           95
2   Ahmed     75    Male           80
3  Ayesha     40  Female           45

# UPDATING VALUES

In [ ]:
ds.loc[0,"Age"] = 26
(ds)

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact,City
0,STU_2024000,26,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral,Karachi
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial,Faisalabad
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral,Rawalpindi
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial,Lahore
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial,Islamabad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial,Multan
4496,STU_2028496,19,Female,Undergraduate,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,Frequently,9.0,83,3.37,Beneficial,Karachi
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial,Faisalabad
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial,Rawalpindi
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial,Lahore

# DELETING A COLUMN AND ROW

In [ ]:
# Deleting a Column
ds = ds.drop("Device_Type", axis=1)
(ds)

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact,City
0,STU_2024000,26,Female,Undergraduate,Snapchat,7.5,1.5,5.9,2,True,Always,20.0,73,2.73,Neutral,Karachi
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial,Faisalabad
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,5.2,1,True,Frequently,18.0,70,3.00,Neutral,Rawalpindi
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial,Lahore
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,7.6,4,True,Never,16.0,84,3.41,Beneficial,Islamabad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial,Multan
4496,STU_2028496,19,Female,Undergraduate,LinkedIn,3.8,3.0,6.6,3,False,Frequently,9.0,83,3.37,Beneficial,Karachi
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,6.0,2,True,Frequently,13.0,73,3.16,Beneficial,Faisalabad
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial,Rawalpindi
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,6.8,3,True,Frequently,10.0,98,3.73,Beneficial,Lahore

In [ ]:
# Deleting a Row
ds = ds.drop(3)
(ds)

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact,City
0,STU_2024000,26,Female,Undergraduate,Snapchat,7.5,1.5,5.9,2,True,Always,20.0,73,2.73,Neutral,Karachi
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial,Faisalabad
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,5.2,1,True,Frequently,18.0,70,3.00,Neutral,Rawalpindi
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,7.6,4,True,Never,16.0,84,3.41,Beneficial,Islamabad
5,STU_2024005,16,Male,High School,TikTok,6.2,1.6,5.9,1,False,Rarely,10.0,66,3.21,Beneficial,Peshawar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial,Multan
4496,STU_2028496,19,Female,Undergraduate,LinkedIn,3.8,3.0,6.6,3,False,Frequently,9.0,83,3.37,Beneficial,Karachi
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,6.0,2,True,Frequently,13.0,73,3.16,Beneficial,Faisalabad
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial,Rawalpindi
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,6.8,3,True,Frequently,10.0,98,3.73,Beneficial,Lahore

In [ ]:
ds = ds.drop(4, axis=0)
ds.loc[4, "Age"] = None
ds.head()

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact,City
0,STU_2024000,26.0,Female,Undergraduate,Snapchat,7.5,1.5,5.9,2.0,True,Always,20.0,73.0,2.73,Neutral,Karachi
1,STU_2024001,19.0,Female,Undergraduate,Instagram,4.6,1.3,7.9,3.0,True,Sometimes,17.0,90.0,3.21,Beneficial,Faisalabad
2,STU_2024002,17.0,Female,High School,TikTok,10.9,1.7,5.2,1.0,True,Frequently,18.0,70.0,3.00,Neutral,Rawalpindi
5,STU_2024005,16.0,Male,High School,TikTok,6.2,1.6,5.9,1.0,False,Rarely,10.0,66.0,3.21,Beneficial,Peshawar
6,STU_2024006,20.0,Male,Undergraduate,TikTok,5.6,1.8,8.3,3.0,False,Sometimes,10.0,88.0,3.72,Beneficial,Quetta

# HANDLING MISSING VALUES

In [ ]:
# 1.Check Missing Values
(ds.isnull().sum())

Student_ID                      1
Age                             1
Gender                          1
Academic_Level                  1
Primary_Platform                1
Daily_Usage_Hours               1
Weekend_Extra_Hours             1
Sleep_Duration_Hours            1
Sleep_Quality_Score             1
Late_Night_Usage                1
Social_Comparison_Frequency     1
Perceived_Stress_Score         47
Mental_Health_Index             1
Academic_Performance_GPA       86
Overall_Impact                  1
City                            1
dtype: int64

In [ ]:
# 2.Remove Missing Values
ds = ds.dropna()
(ds)

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact,City
0,STU_2024000,26.0,Female,Undergraduate,Snapchat,7.5,1.5,5.9,2.0,True,Always,20.0,73.0,2.73,Neutral,Karachi
1,STU_2024001,19.0,Female,Undergraduate,Instagram,4.6,1.3,7.9,3.0,True,Sometimes,17.0,90.0,3.21,Beneficial,Faisalabad
2,STU_2024002,17.0,Female,High School,TikTok,10.9,1.7,5.2,1.0,True,Frequently,18.0,70.0,3.00,Neutral,Rawalpindi
5,STU_2024005,16.0,Male,High School,TikTok,6.2,1.6,5.9,1.0,False,Rarely,10.0,66.0,3.21,Beneficial,Peshawar
6,STU_2024006,20.0,Male,Undergraduate,TikTok,5.6,1.8,8.3,3.0,False,Sometimes,10.0,88.0,3.72,Beneficial,Quetta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,STU_2028495,16.0,Male,High School,YouTube,5.8,1.2,7.8,3.0,True,Sometimes,11.0,79.0,2.85,Beneficial,Multan
4496,STU_2028496,19.0,Female,Undergraduate,LinkedIn,3.8,3.0,6.6,3.0,False,Frequently,9.0,83.0,3.37,Beneficial,Karachi
4497,STU_2028497,19.0,Male,Undergraduate,Instagram,7.7,1.1,6.0,2.0,True,Frequently,13.0,73.0,3.16,Beneficial,Faisalabad
4498,STU_2028498,16.0,Male,High School,LinkedIn,4.6,3.3,7.1,3.0,False,Sometimes,22.0,87.0,3.50,Beneficial,Rawalpindi
4499,STU_2028499,24.0,Male,Undergraduate,Instagram,1.8,2.1,6.8,3.0,True,Frequently,10.0,98.0,3.73,Beneficial,Lahore

In [ ]:
# 3.Fill Missing Values
ds[["Age","Perceived_Stress_Score","Academic_Performance_GPA"]] = ds[["Age","Perceived_Stress_Score","Academic_Performance_GPA"]].fillna(0)
#ds["Daily_Usage_Hours"] = ds["Daily_Usage_Hours"].fillna(ds["Daily_Usage_Hours"].mean())
ds

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact,City
0,STU_2024000,26.0,Female,Undergraduate,Snapchat,7.5,1.5,5.9,2.0,True,Always,20.0,73.0,2.73,Neutral,Karachi
1,STU_2024001,19.0,Female,Undergraduate,Instagram,4.6,1.3,7.9,3.0,True,Sometimes,17.0,90.0,3.21,Beneficial,Faisalabad
2,STU_2024002,17.0,Female,High School,TikTok,10.9,1.7,5.2,1.0,True,Frequently,18.0,70.0,3.00,Neutral,Rawalpindi
5,STU_2024005,16.0,Male,High School,TikTok,6.2,1.6,5.9,1.0,False,Rarely,10.0,66.0,3.21,Beneficial,Peshawar
6,STU_2024006,20.0,Male,Undergraduate,TikTok,5.6,1.8,8.3,3.0,False,Sometimes,10.0,88.0,3.72,Beneficial,Quetta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,STU_2028495,16.0,Male,High School,YouTube,5.8,1.2,7.8,3.0,True,Sometimes,11.0,79.0,2.85,Beneficial,Multan
4496,STU_2028496,19.0,Female,Undergraduate,LinkedIn,3.8,3.0,6.6,3.0,False,Frequently,9.0,83.0,3.37,Beneficial,Karachi
4497,STU_2028497,19.0,Male,Undergraduate,Instagram,7.7,1.1,6.0,2.0,True,Frequently,13.0,73.0,3.16,Beneficial,Faisalabad
4498,STU_2028498,16.0,Male,High School,LinkedIn,4.6,3.3,7.1,3.0,False,Sometimes,22.0,87.0,3.50,Beneficial,Rawalpindi
4499,STU_2028499,24.0,Male,Undergraduate,Instagram,1.8,2.1,6.8,3.0,True,Frequently,10.0,98.0,3.73,Beneficial,Lahore

# AGGREGATION AND GROUPBY

In [ ]:
## These functions help us summarize numerical data.

In [ ]:
# Sum
Perceived_Stress_Score = ds["Perceived_Stress_Score"]
print(Perceived_Stress_Score.sum())

59078.0

In [ ]:
# Average
print(Perceived_Stress_Score.mean())

13.52828028394779

In [ ]:
# Maximum
print(Perceived_Stress_Score.max())

40.0

In [ ]:
# Minimum
print(Perceived_Stress_Score.min())

0.0

In [ ]:
# Count
print(Perceived_Stress_Score.count())

4367

In [ ]:
# Groupby
result = ds.groupby("Student_ID")["Perceived_Stress_Score"].mean()
(result)

Student_ID
STU_2024000    20.0
STU_2024001    17.0
STU_2024002    18.0
STU_2024005    10.0
STU_2024006    10.0
               ...
STU_2028495    11.0
STU_2028496     9.0
STU_2028497    13.0
STU_2028498    22.0
STU_2028499    10.0
Name: Perceived_Stress_Score, Length: 4367, dtype: float64

In [ ]:
print(df.duplicated().sum())

0

# SORTING DATA

In [ ]:
ds = ds.sort_values("Daily_Usage_Hours", ascending= True) #smallest to largest
ds

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact,City
2453,STU_2026453,18.0,Female,Undergraduate,YouTube,0.9,2.4,7.6,5.0,False,Frequently,9.0,93.0,3.59,Beneficial,Peshawar
1473,STU_2025473,15.0,Female,High School,YouTube,1.0,1.1,8.2,4.0,True,Rarely,0.0,98.0,3.64,Beneficial,Faisalabad
294,STU_2024294,19.0,Non-Binary,Undergraduate,Instagram,1.0,3.0,9.2,4.0,True,Frequently,0.0,98.0,4.00,Beneficial,Quetta
3142,STU_2027142,18.0,Male,Undergraduate,TikTok,1.1,2.4,9.4,5.0,True,Never,4.0,98.0,3.71,Beneficial,Quetta
2124,STU_2026124,19.0,Male,Undergraduate,Instagram,1.1,2.8,8.0,3.0,True,Frequently,2.0,96.0,4.00,Beneficial,Islamabad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2091,STU_2026091,17.0,Male,High School,Snapchat,14.0,1.0,4.1,1.0,True,Frequently,31.0,42.0,2.77,Negative,Lahore
89,STU_2024089,18.0,Non-Binary,Undergraduate,Reddit,14.0,1.8,4.7,1.0,True,Frequently,35.0,50.0,2.00,Negative,Faisalabad
2247,STU_2026247,17.0,Female,High School,TikTok,14.0,0.6,4.2,1.0,True,Always,22.0,45.0,2.91,Neutral,Multan
2236,STU_2026236,18.0,Female,Undergraduate,TikTok,14.0,3.4,4.0,1.0,True,Rarely,30.0,46.0,2.43,Negative,Islamabad
2317,STU_2026317,17.0,Female,High School,Instagram,14.0,2.2,3.9,1.0,True,Frequently,32.0,45.0,2.58,Negative,Peshawar

In [ ]:
ds = ds.sort_values("Age", ascending= False) #Largest to smallest
ds

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact,City
167,STU_2024167,26.0,Non-Binary,Postgraduate,Instagram,4.7,1.0,7.0,3.0,False,Frequently,11.0,82.0,3.74,Beneficial,Multan
4198,STU_2028198,26.0,Male,Undergraduate,TikTok,2.5,2.3,7.0,4.0,False,Always,4.0,95.0,3.84,Beneficial,Quetta
368,STU_2024368,26.0,Female,Postgraduate,TikTok,3.9,1.7,6.6,1.0,True,Never,11.0,73.0,3.26,Beneficial,Karachi
1419,STU_2025419,26.0,Female,Postgraduate,Instagram,3.9,1.4,8.3,3.0,False,Rarely,9.0,87.0,3.84,Beneficial,Lahore
59,STU_2024059,26.0,Female,Undergraduate,Instagram,3.1,2.4,8.4,4.0,True,Sometimes,5.0,90.0,4.00,Beneficial,Lahore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1882,STU_2025882,15.0,Male,High School,Reddit,4.8,1.6,6.0,1.0,False,Frequently,10.0,86.0,3.56,Beneficial,Rawalpindi
633,STU_2024633,15.0,Male,High School,Instagram,14.0,1.2,5.3,1.0,True,Sometimes,34.0,54.0,2.74,Negative,Faisalabad
3493,STU_2027493,15.0,Male,High School,Instagram,13.5,1.7,4.2,1.0,True,Frequently,28.0,51.0,2.73,Negative,Peshawar
203,STU_2024203,15.0,Female,High School,YouTube,14.0,1.9,4.8,1.0,True,Frequently,24.0,46.0,3.14,Neutral,Lahore
4228,STU_2028228,15.0,Female,High School,Reddit,1.2,2.0,8.8,4.0,False,Sometimes,15.0,94.0,3.99,Beneficial,Islamabad

# HANDLING DUPLICATE DATA

In [ ]:
# 1.check duplicate data
(ds.duplicated())

167     False
4198    False
368     False
1419    False
59      False
        ...
1882    False
633     False
3493    False
203     False
4228    False
Length: 4367, dtype: bool

In [ ]:
# 2.To count duplicate data
(ds.duplicated().sum())

np.int64(0)

In [ ]:
# 3. To remove duplicate data
ds = ds.drop_duplicates()
ds

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact,City
167,STU_2024167,26.0,Non-Binary,Postgraduate,Instagram,4.7,1.0,7.0,3.0,False,Frequently,11.0,82.0,3.74,Beneficial,Multan
4198,STU_2028198,26.0,Male,Undergraduate,TikTok,2.5,2.3,7.0,4.0,False,Always,4.0,95.0,3.84,Beneficial,Quetta
368,STU_2024368,26.0,Female,Postgraduate,TikTok,3.9,1.7,6.6,1.0,True,Never,11.0,73.0,3.26,Beneficial,Karachi
1419,STU_2025419,26.0,Female,Postgraduate,Instagram,3.9,1.4,8.3,3.0,False,Rarely,9.0,87.0,3.84,Beneficial,Lahore
59,STU_2024059,26.0,Female,Undergraduate,Instagram,3.1,2.4,8.4,4.0,True,Sometimes,5.0,90.0,4.00,Beneficial,Lahore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1882,STU_2025882,15.0,Male,High School,Reddit,4.8,1.6,6.0,1.0,False,Frequently,10.0,86.0,3.56,Beneficial,Rawalpindi
633,STU_2024633,15.0,Male,High School,Instagram,14.0,1.2,5.3,1.0,True,Sometimes,34.0,54.0,2.74,Negative,Faisalabad
3493,STU_2027493,15.0,Male,High School,Instagram,13.5,1.7,4.2,1.0,True,Frequently,28.0,51.0,2.73,Negative,Peshawar
203,STU_2024203,15.0,Female,High School,YouTube,14.0,1.9,4.8,1.0,True,Frequently,24.0,46.0,3.14,Neutral,Lahore
4228,STU_2028228,15.0,Female,High School,Reddit,1.2,2.0,8.8,4.0,False,Sometimes,15.0,94.0,3.99,Beneficial,Islamabad

# COMBINING DATAFRAMES

In [ ]:
# 1.concat()
df1 = pd.DataFrame({
    "Name": ["Azka", "Fatima","Marium"],
    "Marks": [80, 90, 60]
})

df2 = pd.DataFrame({
    "Name": ["Ramsha", "Wajeeha","Maria"],
    "Marks": [75, 85, 65]
})
final_df = pd.concat([df1, df2], ignore_index = True)
final_df

      Name  Marks
0     Azka     80
1   Fatima     90
2   Marium     60
3   Ramsha     75
4  Wajeeha     85
5    Maria     65

In [ ]:
# 2.merge()
students = pd.DataFrame({
    "ID": [19, 16, 21],
    "Name": ["Azka", "Fatima","Marium"]
})

marks = pd.DataFrame({
    "ID": [16, 21, 19],
    "Marks": [80, 90, 75]
})
final_df = pd.merge(students, marks, on="ID")

print(final_df)

   ID    Name  Marks
0  19    Azka     75
1  16  Fatima     80
2  21  Marium     90